name: Invite User to Organization

on:
  issue_comment:
    types: [created]

jobs:
  invite-user:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/invite @')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract username
        id: extract_username
        run: echo "username=$(echo ${{ github.event.comment.body }} | sed -n 's/^.*\/invite @\([a-zA-Z0-9_-]*\).*$/\1/p')" >> $GITHUB_ENV

      - name: Get user ID
        id: get_user_id
        run: |
          USERNAME=${{ env.username }}
          TOKEN=${{ secrets.SECRET_PAT }}
          USER_ID=$(curl -s -H "Authorization: token $TOKEN" \
                       -H "Accept: application/vnd.github.v3+json" \
                       "https://api.github.com/users/$USERNAME" | jq -r '.id')
          echo "user_id=$USER_ID"             
          echo "user_id=$USER_ID" >> "$GITHUB_ENV"

      - name: Invite user to organization
        run: |
          USER_ID=${{ env.user_id }}
          ORG_NAME="Programming-The-Next-Step-2025"
          TOKEN=${{ secrets.SECRET_PAT }}
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $TOKEN" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/orgs/$ORG_NAME/invitations \
            -d "{\"role\":\"direct_member\",\"invitee_id\":$USER_ID}"
