name: Invite User to Organization

on:
  issue_comment:
    types: [created]

jobs:
  invite-user:
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/invite @')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract username
        id: extract_username
        run: echo "username=$(echo ${{ github.event.comment.body }} | sed -n 's/^.*\/invite @\([a-zA-Z0-9_-]*\).*$/\1/p')" >> $GITHUB_ENV

      - name: Invite user to organization
        uses: actions/github-script@v6
        with:
          script: |
            const username = '${{ env.username }}';
            const orgName = 'Programming-The-Next-Step-2025'; // Replace with your organization name
            const token = '${{ secrets.SECRET_PAT }}';

            const { data: user } = await github.rest.users.getByUsername({ username });
            if (user) {
              await github.request({
                method: 'PUT',
                url: `/orgs/${orgName}/invitations`,
                headers: {
                  authorization: `token ${token}`,
                },
                invitee_id: user.id,
              });
              console.log(`Invited ${username} to the organization.`);
            } else {
              console.error(`User ${username} not found.`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
